AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  diehard:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::*:role/diehard'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
      Environment:
        Variables:
          appname: diehard@lambda
          retention_monthly: '13'
          retention_weekly: '13'
          retention_daily: '30'
